version: '3.7'
services:
    bb:
        image: busybox
        volumes:
        - database-data:/var/lib/postgresql/data
        container_name: busybox-1
        hostname: localhost
        networks:
          - default
    db:
        image: postgres:12
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test
        ports:
        - 5432:5432
        hostname: localhost
        volumes:
          - ./pgdata:/var/lib/postgresql/data
        depends_on:
          - bb
        container_name: postgres-1
        networks:
          - default

volumes:
  database-data: # named volumes can be managed easier using docker-compose

#psql -h localhost -p 5432 -U postgres
#docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' a2171d4dcc9e
#postgres://{172.30.0.3}:5432